// File generated by FlutterFire CLI or custom template for StageSync.
// Execute `flutterfire configure` to connect directly to your dedicated Firebase project.
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for StageSync.
/// Run `flutterfire configure` to generate your project-specific credentials.
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDemoKeyForStageSyncWebApp12345678',
    appId: '1:123456789012:web:abcdef1234567890abcdef',
    messagingSenderId: '123456789012',
    projectId: 'stagesync-college-mvp',
    authDomain: 'stagesync-college-mvp.firebaseapp.com',
    storageBucket: 'stagesync-college-mvp.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDemoKeyForStageSyncAndroid12345678',
    appId: '1:123456789012:android:abcdef1234567890abcdef',
    messagingSenderId: '123456789012',
    projectId: 'stagesync-college-mvp',
    storageBucket: 'stagesync-college-mvp.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDemoKeyForStageSyncIOS1234567890ab',
    appId: '1:123456789012:ios:abcdef1234567890abcdef',
    messagingSenderId: '123456789012',
    projectId: 'stagesync-college-mvp',
    storageBucket: 'stagesync-college-mvp.appspot.com',
    iosBundleId: 'com.stagesync.app',
  );
}
